# Generated by Django 6.0.5 on 2026-05-11 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новеллы')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('chapters_count', models.PositiveIntegerField(default=1, verbose_name='Количество глав')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Новелла',
                'verbose_name_plural': 'Новеллы',
                'ordering': ['-published_date', 'title'],
            },
        ),
    ]
