# Generated by Django 6.0.5 on 2026-05-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_novel_slug'),
    ]

    operations = [
    ]
