# Generated by Django 6.0.5 on 2026-05-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20260512_1651'),
    ]

    operations = [
    ]
