# Generated by Django 6.0.5 on 2026-05-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20260512_1708'),
    ]

    operations = [
    ]
