# Generated by Django 6.0.5 on 2026-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_auto_20260512_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('completed', 'Завершено'), ('on_hold', 'На паузе'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
